# 启动端口
server:
  port: 8080

# 配置数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/long_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置MyBatis
mybatis:
  type-aliases-package: com.abraham.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.abraham: debug
  file:
    name: log/blog-dev.log

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
